
CONFIG_TRACE  = 1
CONFIG_ITRACE = 1
CONFIG_MTRACE = 0
# CONFIG_FTRACE = 1

CONFIG_DIFFTEST = 1

CONFIG_TRACE_START = 0
CONFIG_TRACE_END   = 10000
CONFIG_MTRACE_BASE = 0x00000000
CONFIG_MTRACE_SIZE = 0x1000

# CONFIG_LOOP_DETECT = 1

ifeq ($(CONFIG_TRACE), 1)

CXXFLAGS += -DCONFIG_TRACE=1

ifeq ($(CONFIG_ITRACE), 1)
CXXFLAGS += -DCONFIG_ITRACE=1
endif

ifeq ($(CONFIG_MTRACE), 1)
CXXFLAGS += -DCONFIG_MTRACE=1
endif

ifeq ($(CONFIG_FTRACE), 1)
CXXFLAGS += -DCONFIG_FTRACE=1
endif

CXXFLAGS += -DCONFIG_MTRACE_BASE=$(CONFIG_MTRACE_BASE) -DCONFIG_MTRACE_SIZE=$(CONFIG_MTRACE_SIZE)
CXXFLAGS += -DCONFIG_TRACE_START=$(CONFIG_TRACE_START) -DCONFIG_TRACE_END=$(CONFIG_TRACE_END)

endif

ifeq ($(CONFIG_DIFFTEST), 1)
CXXFLAGS += -DCONFIG_DIFFTEST=1
endif

ifeq ($(CONFIG_LOOP_DETECT), 1)
CXXFLAGS += -DCONFIG_LOOP_DETECT=1
endif