
module top
(
    input         clock,
    input         reset
);

    //cpu core
    wire        cpu_awvalid;
    wire        cpu_awready;
    wire [31:0] cpu_awaddr;
    wire [3:0 ] cpu_awid;
    wire [7:0 ] cpu_awlen;
    wire [2:0 ] cpu_awsize;
    wire [1:0 ] cpu_awburst;
    wire        cpu_wvalid;
    wire        cpu_wready;
    wire [31:0] cpu_wdata;
    wire [3:0 ] cpu_wstrb;
    wire        cpu_wlast;
    wire        cpu_bvalid;
    wire        cpu_bready;
    wire [1:0]  cpu_bresp;
    wire [3:0 ] cpu_bid;
    wire        cpu_arvalid;
    wire        cpu_arready;
    wire [31:0] cpu_araddr;
    wire [3:0 ] cpu_arid;
    wire [7:0 ] cpu_arlen;
    wire [2:0 ] cpu_arsize;
    wire [1:0 ] cpu_arburst;
    wire        cpu_rvalid;
    wire        cpu_rready;
    wire [31:0] cpu_rdata;
    wire [1:0]  cpu_rresp;
    wire        cpu_rlast;
    wire [3:0 ] cpu_rid;

    wire        s0_awvalid;
    wire        s0_awready;
    wire [31:0] s0_awaddr;
    wire [3:0 ] s0_awid;
    wire [7:0 ] s0_awlen;
    wire [2:0 ] s0_awsize;
    wire [1:0 ] s0_awburst;
    wire        s0_wvalid;
    wire        s0_wready;
    wire [31:0] s0_wdata;
    wire [3:0 ] s0_wstrb;
    wire        s0_wlast;
    wire        s0_bvalid;
    wire        s0_bready;
    wire [1:0]  s0_bresp;
    wire [3:0 ] s0_bid;
    wire        s0_arvalid;
    wire        s0_arready;
    wire [31:0] s0_araddr;
    wire [3:0 ] s0_arid;
    wire [7:0 ] s0_arlen;
    wire [2:0 ] s0_arsize;
    wire [1:0 ] s0_arburst;
    wire        s0_rvalid;
    wire        s0_rready;
    wire [31:0] s0_rdata;
    wire [1:0]  s0_rresp;
    wire        s0_rlast;
    wire [3:0 ] s0_rid;

    wire        s1_awvalid;
    wire        s1_awready;
    wire [31:0] s1_awaddr;
    wire [3:0 ] s1_awid;
    wire [7:0 ] s1_awlen;
    wire [2:0 ] s1_awsize;
    wire [1:0 ] s1_awburst;
    wire        s1_wvalid;
    wire        s1_wready;
    wire [31:0] s1_wdata;
    wire [3:0 ] s1_wstrb;
    wire        s1_wlast;
    wire        s1_bvalid;
    wire        s1_bready;
    wire [1:0]  s1_bresp;
    wire [3:0 ] s1_bid;
    wire        s1_arvalid;
    wire        s1_arready;
    wire [31:0] s1_araddr;
    wire [3:0 ] s1_arid;
    wire [7:0 ] s1_arlen;
    wire [2:0 ] s1_arsize;
    wire [1:0 ] s1_arburst;
    wire        s1_rvalid;
    wire        s1_rready;
    wire [31:0] s1_rdata;
    wire [1:0]  s1_rresp;
    wire        s1_rlast;
    wire [3:0 ] s1_rid;

    ysyx_25110270 ysyx_25110270(
        .clock(clock),
        .reset(reset),
        .io_interrupt(1'b0),
        .io_master_awvalid(cpu_awvalid),
        .io_master_awready(cpu_awready),
        .io_master_awaddr_0_(cpu_awaddr[0]),
        .io_master_awaddr_1_(cpu_awaddr[1]),
        .io_master_awaddr_2_(cpu_awaddr[2]),
        .io_master_awaddr_3_(cpu_awaddr[3]),
        .io_master_awaddr_4_(cpu_awaddr[4]),
        .io_master_awaddr_5_(cpu_awaddr[5]),
        .io_master_awaddr_6_(cpu_awaddr[6]),
        .io_master_awaddr_7_(cpu_awaddr[7]),
        .io_master_awaddr_8_(cpu_awaddr[8]),
        .io_master_awaddr_9_(cpu_awaddr[9]),
        .io_master_awaddr_10_(cpu_awaddr[10]),
        .io_master_awaddr_11_(cpu_awaddr[11]),
        .io_master_awaddr_12_(cpu_awaddr[12]),
        .io_master_awaddr_13_(cpu_awaddr[13]),
        .io_master_awaddr_14_(cpu_awaddr[14]),
        .io_master_awaddr_15_(cpu_awaddr[15]),
        .io_master_awaddr_16_(cpu_awaddr[16]),
        .io_master_awaddr_17_(cpu_awaddr[17]),
        .io_master_awaddr_18_(cpu_awaddr[18]),
        .io_master_awaddr_19_(cpu_awaddr[19]),
        .io_master_awaddr_20_(cpu_awaddr[20]),
        .io_master_awaddr_21_(cpu_awaddr[21]),
        .io_master_awaddr_22_(cpu_awaddr[22]),
        .io_master_awaddr_23_(cpu_awaddr[23]),
        .io_master_awaddr_24_(cpu_awaddr[24]),
        .io_master_awaddr_25_(cpu_awaddr[25]),
        .io_master_awaddr_26_(cpu_awaddr[26]),
        .io_master_awaddr_27_(cpu_awaddr[27]),
        .io_master_awaddr_28_(cpu_awaddr[28]),
        .io_master_awaddr_29_(cpu_awaddr[29]),
        .io_master_awaddr_30_(cpu_awaddr[30]),
        .io_master_awaddr_31_(cpu_awaddr[31]),
        .io_master_awid_0_(cpu_awid[0]),
        .io_master_awid_1_(cpu_awid[1]),
        .io_master_awid_2_(cpu_awid[2]),
        .io_master_awid_3_(cpu_awid[3]),
        .io_master_awlen_0_(cpu_awlen[0]),
        .io_master_awlen_1_(cpu_awlen[1]),
        .io_master_awlen_2_(cpu_awlen[2]),
        .io_master_awlen_3_(cpu_awlen[3]),
        .io_master_awlen_4_(cpu_awlen[4]),
        .io_master_awlen_5_(cpu_awlen[5]),
        .io_master_awlen_6_(cpu_awlen[6]),
        .io_master_awlen_7_(cpu_awlen[7]),
        .io_master_awsize_0_(cpu_awsize[0]),
        .io_master_awsize_1_(cpu_awsize[1]),
        .io_master_awsize_2_(cpu_awsize[2]),
        .io_master_awburst_0_(cpu_awburst[0]),
        .io_master_awburst_1_(cpu_awburst[1]),
        .io_master_wvalid(cpu_wvalid),
        .io_master_wready(cpu_wready),
        .io_master_wdata_0_(cpu_wdata[0]),
        .io_master_wdata_1_(cpu_wdata[1]),
        .io_master_wdata_2_(cpu_wdata[2]),
        .io_master_wdata_3_(cpu_wdata[3]),
        .io_master_wdata_4_(cpu_wdata[4]),
        .io_master_wdata_5_(cpu_wdata[5]),
        .io_master_wdata_6_(cpu_wdata[6]),
        .io_master_wdata_7_(cpu_wdata[7]),
        .io_master_wdata_8_(cpu_wdata[8]),
        .io_master_wdata_9_(cpu_wdata[9]),
        .io_master_wdata_10_(cpu_wdata[10]),
        .io_master_wdata_11_(cpu_wdata[11]),
        .io_master_wdata_12_(cpu_wdata[12]),
        .io_master_wdata_13_(cpu_wdata[13]),
        .io_master_wdata_14_(cpu_wdata[14]),
        .io_master_wdata_15_(cpu_wdata[15]),
        .io_master_wdata_16_(cpu_wdata[16]),
        .io_master_wdata_17_(cpu_wdata[17]),
        .io_master_wdata_18_(cpu_wdata[18]),
        .io_master_wdata_19_(cpu_wdata[19]),
        .io_master_wdata_20_(cpu_wdata[20]),
        .io_master_wdata_21_(cpu_wdata[21]),
        .io_master_wdata_22_(cpu_wdata[22]),
        .io_master_wdata_23_(cpu_wdata[23]),
        .io_master_wdata_24_(cpu_wdata[24]),
        .io_master_wdata_25_(cpu_wdata[25]),
        .io_master_wdata_26_(cpu_wdata[26]),
        .io_master_wdata_27_(cpu_wdata[27]),
        .io_master_wdata_28_(cpu_wdata[28]),
        .io_master_wdata_29_(cpu_wdata[29]),
        .io_master_wdata_30_(cpu_wdata[30]),
        .io_master_wdata_31_(cpu_wdata[31]),
        .io_master_wstrb_0_(cpu_wstrb[0]),
        .io_master_wstrb_1_(cpu_wstrb[1]),
        .io_master_wstrb_2_(cpu_wstrb[2]),
        .io_master_wstrb_3_(cpu_wstrb[3]),
        .io_master_wlast(cpu_wlast),
        .io_master_bvalid(cpu_bvalid),
        .io_master_bready(cpu_bready),
        .io_master_bresp_0_(cpu_bresp[0]),
        .io_master_bresp_1_(cpu_bresp[1]),
        .io_master_bid_0_(cpu_bid[0]),
        .io_master_bid_1_(cpu_bid[1]),
        .io_master_bid_2_(cpu_bid[2]),
        .io_master_bid_3_(cpu_bid[3]),
        .io_master_arvalid(cpu_arvalid),
        .io_master_arready(cpu_arready),
        .io_master_araddr_0_(cpu_araddr[0]),
        .io_master_araddr_1_(cpu_araddr[1]),
        .io_master_araddr_2_(cpu_araddr[2]),
        .io_master_araddr_3_(cpu_araddr[3]),
        .io_master_araddr_4_(cpu_araddr[4]),
        .io_master_araddr_5_(cpu_araddr[5]),
        .io_master_araddr_6_(cpu_araddr[6]),
        .io_master_araddr_7_(cpu_araddr[7]),
        .io_master_araddr_8_(cpu_araddr[8]),
        .io_master_araddr_9_(cpu_araddr[9]),
        .io_master_araddr_10_(cpu_araddr[10]),
        .io_master_araddr_11_(cpu_araddr[11]),
        .io_master_araddr_12_(cpu_araddr[12]),
        .io_master_araddr_13_(cpu_araddr[13]),
        .io_master_araddr_14_(cpu_araddr[14]),
        .io_master_araddr_15_(cpu_araddr[15]),
        .io_master_araddr_16_(cpu_araddr[16]),
        .io_master_araddr_17_(cpu_araddr[17]),
        .io_master_araddr_18_(cpu_araddr[18]),
        .io_master_araddr_19_(cpu_araddr[19]),
        .io_master_araddr_20_(cpu_araddr[20]),
        .io_master_araddr_21_(cpu_araddr[21]),
        .io_master_araddr_22_(cpu_araddr[22]),
        .io_master_araddr_23_(cpu_araddr[23]),
        .io_master_araddr_24_(cpu_araddr[24]),
        .io_master_araddr_25_(cpu_araddr[25]),
        .io_master_araddr_26_(cpu_araddr[26]),
        .io_master_araddr_27_(cpu_araddr[27]),
        .io_master_araddr_28_(cpu_araddr[28]),
        .io_master_araddr_29_(cpu_araddr[29]),
        .io_master_araddr_30_(cpu_araddr[30]),
        .io_master_araddr_31_(cpu_araddr[31]),
        .io_master_arid_0_(cpu_arid[0]),
        .io_master_arid_1_(cpu_arid[1]),
        .io_master_arid_2_(cpu_arid[2]),
        .io_master_arid_3_(cpu_arid[3]),
        .io_master_arlen_0_(cpu_arlen[0]),
        .io_master_arlen_1_(cpu_arlen[1]),
        .io_master_arlen_2_(cpu_arlen[2]),
        .io_master_arlen_3_(cpu_arlen[3]),
        .io_master_arlen_4_(cpu_arlen[4]),
        .io_master_arlen_5_(cpu_arlen[5]),
        .io_master_arlen_6_(cpu_arlen[6]),
        .io_master_arlen_7_(cpu_arlen[7]),
        .io_master_arsize_0_(cpu_arsize[0]),
        .io_master_arsize_1_(cpu_arsize[1]),
        .io_master_arsize_2_(cpu_arsize[2]),
        .io_master_arburst_0_(cpu_arburst[0]),
        .io_master_arburst_1_(cpu_arburst[1]),
        .io_master_rvalid(cpu_rvalid),
        .io_master_rready(cpu_rready),
        .io_master_rdata_0_(cpu_rdata[0]),
        .io_master_rdata_1_(cpu_rdata[1]),
        .io_master_rdata_2_(cpu_rdata[2]),
        .io_master_rdata_3_(cpu_rdata[3]),
        .io_master_rdata_4_(cpu_rdata[4]),
        .io_master_rdata_5_(cpu_rdata[5]),
        .io_master_rdata_6_(cpu_rdata[6]),
        .io_master_rdata_7_(cpu_rdata[7]),
        .io_master_rdata_8_(cpu_rdata[8]),
        .io_master_rdata_9_(cpu_rdata[9]),
        .io_master_rdata_10_(cpu_rdata[10]),
        .io_master_rdata_11_(cpu_rdata[11]),
        .io_master_rdata_12_(cpu_rdata[12]),
        .io_master_rdata_13_(cpu_rdata[13]),
        .io_master_rdata_14_(cpu_rdata[14]),
        .io_master_rdata_15_(cpu_rdata[15]),
        .io_master_rdata_16_(cpu_rdata[16]),
        .io_master_rdata_17_(cpu_rdata[17]),
        .io_master_rdata_18_(cpu_rdata[18]),
        .io_master_rdata_19_(cpu_rdata[19]),
        .io_master_rdata_20_(cpu_rdata[20]),
        .io_master_rdata_21_(cpu_rdata[21]),
        .io_master_rdata_22_(cpu_rdata[22]),
        .io_master_rdata_23_(cpu_rdata[23]),
        .io_master_rdata_24_(cpu_rdata[24]),
        .io_master_rdata_25_(cpu_rdata[25]),
        .io_master_rdata_26_(cpu_rdata[26]),
        .io_master_rdata_27_(cpu_rdata[27]),
        .io_master_rdata_28_(cpu_rdata[28]),
        .io_master_rdata_29_(cpu_rdata[29]),
        .io_master_rdata_30_(cpu_rdata[30]),
        .io_master_rdata_31_(cpu_rdata[31]),
        .io_master_rresp_0_(cpu_rresp[0]),
        .io_master_rresp_1_(cpu_rresp[1]),
        .io_master_rlast(cpu_rlast),
        .io_master_rid_0_(cpu_rid[0]),
        .io_master_rid_1_(cpu_rid[1]),
        .io_master_rid_2_(cpu_rid[2]),
        .io_master_rid_3_(cpu_rid[3]),

        .io_slave_awvalid(1'b0),
        .io_slave_awready(),
        .io_slave_awaddr_0_(1'b0),
        .io_slave_awaddr_1_(1'b0),
        .io_slave_awaddr_2_(1'b0),
        .io_slave_awaddr_3_(1'b0),
        .io_slave_awaddr_4_(1'b0),
        .io_slave_awaddr_5_(1'b0),
        .io_slave_awaddr_6_(1'b0),
        .io_slave_awaddr_7_(1'b0),
        .io_slave_awaddr_8_(1'b0),
        .io_slave_awaddr_9_(1'b0),
        .io_slave_awaddr_10_(1'b0),
        .io_slave_awaddr_11_(1'b0),
        .io_slave_awaddr_12_(1'b0),
        .io_slave_awaddr_13_(1'b0),
        .io_slave_awaddr_14_(1'b0),
        .io_slave_awaddr_15_(1'b0),
        .io_slave_awaddr_16_(1'b0),
        .io_slave_awaddr_17_(1'b0),
        .io_slave_awaddr_18_(1'b0),
        .io_slave_awaddr_19_(1'b0),
        .io_slave_awaddr_20_(1'b0),
        .io_slave_awaddr_21_(1'b0),
        .io_slave_awaddr_22_(1'b0),
        .io_slave_awaddr_23_(1'b0),
        .io_slave_awaddr_24_(1'b0),
        .io_slave_awaddr_25_(1'b0),
        .io_slave_awaddr_26_(1'b0),
        .io_slave_awaddr_27_(1'b0),
        .io_slave_awaddr_28_(1'b0),
        .io_slave_awaddr_29_(1'b0),
        .io_slave_awaddr_30_(1'b0),
        .io_slave_awaddr_31_(1'b0),
        .io_slave_awid_0_(1'b0),
        .io_slave_awid_1_(1'b0),
        .io_slave_awid_2_(1'b0),
        .io_slave_awid_3_(1'b0),
        .io_slave_awlen_0_(1'b0),
        .io_slave_awlen_1_(1'b0),
        .io_slave_awlen_2_(1'b0),
        .io_slave_awlen_3_(1'b0),
        .io_slave_awlen_4_(1'b0),
        .io_slave_awlen_5_(1'b0),
        .io_slave_awlen_6_(1'b0),
        .io_slave_awlen_7_(1'b0),
        .io_slave_awsize_0_(1'b0),
        .io_slave_awsize_1_(1'b0),
        .io_slave_awsize_2_(1'b0),
        .io_slave_awburst_0_(1'b0),
        .io_slave_awburst_1_(1'b0),
        .io_slave_wvalid(1'b0),
        .io_slave_wready(),
        .io_slave_wdata_0_(1'b0),
        .io_slave_wdata_1_(1'b0),
        .io_slave_wdata_2_(1'b0),
        .io_slave_wdata_3_(1'b0),
        .io_slave_wdata_4_(1'b0),
        .io_slave_wdata_5_(1'b0),
        .io_slave_wdata_6_(1'b0),
        .io_slave_wdata_7_(1'b0),
        .io_slave_wdata_8_(1'b0),
        .io_slave_wdata_9_(1'b0),
        .io_slave_wdata_10_(1'b0),
        .io_slave_wdata_11_(1'b0),
        .io_slave_wdata_12_(1'b0),
        .io_slave_wdata_13_(1'b0),
        .io_slave_wdata_14_(1'b0),
        .io_slave_wdata_15_(1'b0),
        .io_slave_wdata_16_(1'b0),
        .io_slave_wdata_17_(1'b0),
        .io_slave_wdata_18_(1'b0),
        .io_slave_wdata_19_(1'b0),
        .io_slave_wdata_20_(1'b0),
        .io_slave_wdata_21_(1'b0),
        .io_slave_wdata_22_(1'b0),
        .io_slave_wdata_23_(1'b0),
        .io_slave_wdata_24_(1'b0),
        .io_slave_wdata_25_(1'b0),
        .io_slave_wdata_26_(1'b0),
        .io_slave_wdata_27_(1'b0),
        .io_slave_wdata_28_(1'b0),
        .io_slave_wdata_29_(1'b0),
        .io_slave_wdata_30_(1'b0),
        .io_slave_wdata_31_(1'b0),
        .io_slave_wstrb_0_(1'b0),
        .io_slave_wstrb_1_(1'b0),
        .io_slave_wstrb_2_(1'b0),
        .io_slave_wstrb_3_(1'b0),
        .io_slave_wlast(1'b0),
        .io_slave_bvalid(),
        .io_slave_bready(1'b0),
        .io_slave_bresp_0_(),
        .io_slave_bresp_1_(),
        .io_slave_bid_0_(),
        .io_slave_bid_1_(),
        .io_slave_bid_2_(),
        .io_slave_bid_3_(),
        .io_slave_arvalid(1'b0),
        .io_slave_arready(),
        .io_slave_araddr_0_(1'b0),
        .io_slave_araddr_1_(1'b0),
        .io_slave_araddr_2_(1'b0),
        .io_slave_araddr_3_(1'b0),
        .io_slave_araddr_4_(1'b0),
        .io_slave_araddr_5_(1'b0),
        .io_slave_araddr_6_(1'b0),
        .io_slave_araddr_7_(1'b0),
        .io_slave_araddr_8_(1'b0),
        .io_slave_araddr_9_(1'b0),
        .io_slave_araddr_10_(1'b0),
        .io_slave_araddr_11_(1'b0),
        .io_slave_araddr_12_(1'b0),
        .io_slave_araddr_13_(1'b0),
        .io_slave_araddr_14_(1'b0),
        .io_slave_araddr_15_(1'b0),
        .io_slave_araddr_16_(1'b0),
        .io_slave_araddr_17_(1'b0),
        .io_slave_araddr_18_(1'b0),
        .io_slave_araddr_19_(1'b0),
        .io_slave_araddr_20_(1'b0),
        .io_slave_araddr_21_(1'b0),
        .io_slave_araddr_22_(1'b0),
        .io_slave_araddr_23_(1'b0),
        .io_slave_araddr_24_(1'b0),
        .io_slave_araddr_25_(1'b0),
        .io_slave_araddr_26_(1'b0),
        .io_slave_araddr_27_(1'b0),
        .io_slave_araddr_28_(1'b0),
        .io_slave_araddr_29_(1'b0),
        .io_slave_araddr_30_(1'b0),
        .io_slave_araddr_31_(1'b0),
        .io_slave_arid_0_(1'b0),
        .io_slave_arid_1_(1'b0),
        .io_slave_arid_2_(1'b0),
        .io_slave_arid_3_(1'b0),
        .io_slave_arlen_0_(1'b0),
        .io_slave_arlen_1_(1'b0),
        .io_slave_arlen_2_(1'b0),
        .io_slave_arlen_3_(1'b0),
        .io_slave_arlen_4_(1'b0),
        .io_slave_arlen_5_(1'b0),
        .io_slave_arlen_6_(1'b0),
        .io_slave_arlen_7_(1'b0),
        .io_slave_arsize_0_(1'b0),
        .io_slave_arsize_1_(1'b0),
        .io_slave_arsize_2_(1'b0),
        .io_slave_arburst_0_(1'b0),
        .io_slave_arburst_1_(1'b0),
        .io_slave_rvalid(),
        .io_slave_rready(1'b0),
        .io_slave_rdata_0_(),
        .io_slave_rdata_1_(),
        .io_slave_rdata_2_(),
        .io_slave_rdata_3_(),
        .io_slave_rdata_4_(),
        .io_slave_rdata_5_(),
        .io_slave_rdata_6_(),
        .io_slave_rdata_7_(),
        .io_slave_rdata_8_(),
        .io_slave_rdata_9_(),
        .io_slave_rdata_10_(),
        .io_slave_rdata_11_(),
        .io_slave_rdata_12_(),
        .io_slave_rdata_13_(),
        .io_slave_rdata_14_(),
        .io_slave_rdata_15_(),
        .io_slave_rdata_16_(),
        .io_slave_rdata_17_(),
        .io_slave_rdata_18_(),
        .io_slave_rdata_19_(),
        .io_slave_rdata_20_(),
        .io_slave_rdata_21_(),
        .io_slave_rdata_22_(),
        .io_slave_rdata_23_(),
        .io_slave_rdata_24_(),
        .io_slave_rdata_25_(),
        .io_slave_rdata_26_(),
        .io_slave_rdata_27_(),
        .io_slave_rdata_28_(),
        .io_slave_rdata_29_(),
        .io_slave_rdata_30_(),
        .io_slave_rdata_31_(),
        .io_slave_rresp_0_(),
        .io_slave_rresp_1_(),
        .io_slave_rlast(),
        .io_slave_rid_0_(),
        .io_slave_rid_1_(),
        .io_slave_rid_2_(),
        .io_slave_rid_3_()
    );


    mem mem_test
    (
        .clk(clock),
        .rst(reset),
        .awvalid_i(s0_awvalid),
        .awready_o(s0_awready),
        .awaddr_i(s0_awaddr),
        .awid_i(s0_awid),
        .awlen_i(s0_awlen),
        .awsize_i(s0_awsize),
        .awburst_i(s0_awburst),
        .wvalid_i(s0_wvalid),
        .wready_o(s0_wready),
        .wdata_i(s0_wdata),
        .wstrb_i(s0_wstrb),
        .wlast_i(s0_wlast),
        .bvalid_o(s0_bvalid),
        .bready_i(s0_bready),
        .bresp_o(s0_bresp),
        .bid_o(s0_bid),
        .arvalid_i(s0_arvalid),
        .arready_o(s0_arready),
        .araddr_i(s0_araddr),
        .arid_i(s0_arid),
        .arlen_i(s0_arlen),
        .arsize_i(s0_arsize),
        .arburst_i(s0_arburst),
        .rvalid_o(s0_rvalid),
        .rready_i(s0_rready),
        .rdata_o(s0_rdata),
        .rresp_o(s0_rresp),
        .rlast_o(s0_rlast),
        .rid_o(s0_rid)
    );

    uart uart_test(
        .clk(clock),
        .rst(reset),
        .awvalid_i(s1_awvalid),
        .awready_o(s1_awready),
        .awaddr_i(s1_awaddr),
        .awid_i(s1_awid),
        .awlen_i(s1_awlen),
        .awsize_i(s1_awsize),
        .awburst_i(s1_awburst),
        .wvalid_i(s1_wvalid),
        .wready_o(s1_wready),
        .wdata_i(s1_wdata),
        .wstrb_i(s1_wstrb),
        .wlast_i(s1_wlast),
        .bvalid_o(s1_bvalid),
        .bready_i(s1_bready),
        .bresp_o(s1_bresp),
        .bid_o(s1_bid),
        .arvalid_i(s1_arvalid),
        .arready_o(s1_arready),
        .araddr_i(s1_araddr),
        .arid_i(s1_arid),
        .arlen_i(s1_arlen),
        .arsize_i(s1_arsize),
        .arburst_i(s1_arburst),
        .rvalid_o(s1_rvalid),
        .rready_i(s1_rready),
        .rdata_o(s1_rdata),
        .rresp_o(s1_rresp),
        .rlast_o(s1_rlast),
        .rid_o(s1_rid)
    );


    test_xbar
    #(
        .S0_BASE(32'ha000_0000),
        .S0_SIZE(32'h0800_0000)
    ) xbar_test
    (
        .clk(clock),
        .rst(reset),

        .S_arvalid(cpu_arvalid),
        .S_arready(cpu_arready),
        .S_arid(cpu_arid),
        .S_araddr(cpu_araddr),
        .S_arlen(cpu_arlen),
        .S_arsize(cpu_arsize),
        .S_arburst(cpu_arburst),
        .S_rready(cpu_rready),
        .S_rvalid(cpu_rvalid),
        .S_rid(cpu_rid),
        .S_rdata(cpu_rdata),
        .S_rresp(cpu_rresp),
        .S_rlast(cpu_rlast),
        .S_awvalid(cpu_awvalid),
        .S_awready(cpu_awready),
        .S_awid(cpu_awid),
        .S_awaddr(cpu_awaddr),
        .S_awlen(cpu_awlen),
        .S_awsize(cpu_awsize),
        .S_awburst(cpu_awburst),
        .S_wvalid(cpu_wvalid),
        .S_wready(cpu_wready),
        .S_wdata(cpu_wdata),
        .S_wstrb(cpu_wstrb),
        .S_wlast(cpu_wlast),
        .S_bready(cpu_bready),
        .S_bvalid(cpu_bvalid),
        .S_bid(cpu_bid),
        .S_bresp(cpu_bresp),

        .M0_awvalid(s0_awvalid),
        .M0_awready(s0_awready),
        .M0_awid(s0_awid),
        .M0_awaddr(s0_awaddr),
        .M0_awlen(s0_awlen),
        .M0_awsize(s0_awsize),
        .M0_awburst(s0_awburst),
        .M0_wvalid(s0_wvalid),
        .M0_wready(s0_wready),
        .M0_wdata(s0_wdata),
        .M0_wstrb(s0_wstrb),
        .M0_wlast(s0_wlast),
        .M0_bvalid(s0_bvalid),
        .M0_bready(s0_bready),
        .M0_bresp(s0_bresp),
        .M0_bid(s0_bid),
        .M0_arvalid(s0_arvalid),
        .M0_arready(s0_arready),
        .M0_arid(s0_arid),
        .M0_araddr(s0_araddr),
        .M0_arlen(s0_arlen),
        .M0_arsize(s0_arsize),
        .M0_arburst(s0_arburst),
        .M0_rvalid(s0_rvalid),
        .M0_rready(s0_rready),
        .M0_rid(s0_rid),
        .M0_rdata(s0_rdata),
        .M0_rresp(s0_rresp),
        .M0_rlast(s0_rlast),

        .M1_awvalid(s1_awvalid),
        .M1_awready(s1_awready),
        .M1_awid(s1_awid),
        .M1_awaddr(s1_awaddr),
        .M1_awlen(s1_awlen),
        .M1_awsize(s1_awsize),
        .M1_awburst(s1_awburst),
        .M1_wvalid(s1_wvalid),
        .M1_wready(s1_wready),
        .M1_wdata(s1_wdata),
        .M1_wstrb(s1_wstrb),
        .M1_wlast(s1_wlast),
        .M1_bvalid(s1_bvalid),
        .M1_bready(s1_bready),
        .M1_bresp(s1_bresp),
        .M1_bid(s1_bid),
        .M1_arvalid(s1_arvalid),
        .M1_arready(s1_arready),
        .M1_arid(s1_arid),
        .M1_araddr(s1_araddr),
        .M1_arlen(s1_arlen),
        .M1_arsize(s1_arsize),
        .M1_arburst(s1_arburst),
        .M1_rvalid(s1_rvalid),
        .M1_rready(s1_rready),
        .M1_rid(s1_rid),
        .M1_rdata(s1_rdata),
        .M1_rresp(s1_rresp),
        .M1_rlast(s1_rlast)
    );

endmodule
